"""add_ping

Revision ID: f0f9e5fe52fb
Revises: c74c3a14facb
Create Date: 2021-11-17 22:59:57.435156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f9e5fe52fb'
down_revision = 'c74c3a14facb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.Column('desc', sa.String(length=32), nullable=False, comment='描述'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_ping_create_time'), 'ping', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ping_create_time'), table_name='ping')
    op.drop_table('ping')
    # ### end Alembic commands ###
